package com.morty.c137.po;

import java.util.Date;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.id
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.name
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.desc
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.create_time
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.update_time
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.id
     *
     * @return the value of job.id
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.id
     *
     * @param id the value for job.id
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.name
     *
     * @return the value of job.name
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.name
     *
     * @param name the value for job.name
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.desc
     *
     * @return the value of job.desc
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.desc
     *
     * @param desc the value for job.desc
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.create_time
     *
     * @return the value of job.create_time
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.create_time
     *
     * @param createTime the value for job.create_time
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.update_time
     *
     * @return the value of job.update_time
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.update_time
     *
     * @param updateTime the value for job.update_time
     *
     * @mbg.generated Sat Aug 18 11:27:35 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}